parties/parties/urls.py
from django.contrib import admin
from django.urls import include, path
from django.http import HttpResponseRedirect

urlpatterns = [
    path('', lambda r: HttpResponseRedirect('partyfinder/')),
    path('partyfinder/', include('partyfinder.urls')),
    path('admin/', admin.site.urls),
]

parties/partyfinder/urls.py
from django.urls import path

from . import views

app_name = 'partyfinder'
urlpatterns = [
  path('', views.index, name='index'),
  path('list/<str:city>/', views.parties, name='parties'),
  path('new/', views.new_party, name='new_party'),
  path('detail/<str:city>/<str:id>', views.party, name='party'),
  path('delete/<str:city>/<str:id>', views.delete_party, name='delete_party'),
  path('change_people/<str:city>/<str:id>/<int:prev_value>/<str:delta>', views.change_party_people, name='change_party_people'),
  # 'delta' above is a string to allow for '-1' and '+1'
]

parties/partyfinder/models.py
import uuid

from django.utils import timezone

from cassandra.cqlengine import columns
from django_cassandra_engine.models import DjangoCassandraModel

# A model for this app
class Party(DjangoCassandraModel):
  city = columns.Text(
    primary_key=True,
  )
  id = columns.UUID(
    primary_key=True,
    clustering_order='asc', # (allowed: 'asc' , 'desc', lowercase)
    default=uuid.uuid4,
  )
  name = columns.Text()
  people = columns.Integer(default=0)
  date = columns.DateTime(default=timezone.now)

  class Meta:
    get_pk_field='id'

parties/partyfinder/forms.py
from django import forms

class PartyForm(forms.Form):
    city = forms.CharField(label='City', max_length=50)
    name = forms.CharField(label='Name', max_length=200)
    date = forms.DateField(label='Date (YYYY-MM-DD)', input_formats=['%Y-%m-%d'])
    people = forms.IntegerField(label='People', min_value=0)

class CityForm(forms.Form):
    city = forms.CharField(label='Browse city:', max_length=50)

parties/partyfinder/views.py
import uuid
import datetime

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.urls import reverse
from django.db import connection

from .models import Party
from .forms import PartyForm, CityForm

# Create your views here.
def index(request):
  if request.method == 'POST':
    form = CityForm(request.POST)
    if form.is_valid():
      return HttpResponseRedirect(reverse(
        'partyfinder:parties',
        kwargs={
          'city': form.cleaned_data['city'],
        },
      ))
    else:
      return HttpResponseRedirect(reverse('partyfinder:index'))
  else:
    form = CityForm()
  return render(
    request,
    'partyfinder/index.html',
    context={
      'form': form,
    },
  )

def party(request, city, id):
  # are we here with a "could not update 'people'" message to display?
  lwt_failed = request.GET.get('LWT_FAILED', False)
  #
  parties = Party.objects.filter(city=city, id=id)
  if len(parties)> 0:
    party = parties[0]
    context = {
      'party': party,
      'lwt_failed': lwt_failed,
    }
    return render(
      request,
      'partyfinder/party.html',
      context,
    )
  else:
    raise Http404

def parties(request, city):
  parties = Party.objects.filter(city=city).order_by('-date')
  context = {
    'city': city,
    'parties': parties,
  }
  
  return render(
    request,
    'partyfinder/list.html',
    context,
  )

def new_party(request):
  if request.method == 'POST':
    form = PartyForm(request.POST)
    if form.is_valid():
      #
      party = Party(
        **form.cleaned_data,
      )
      party.save()
      #
      return HttpResponseRedirect(reverse(
        'partyfinder:parties',
        kwargs={
          'city': form.cleaned_data['city'],
        },
      ))
  else:
    default_city = request.GET.get('city')
    f_initial = {}
    if default_city is not None:
      f_initial['city'] = default_city
    f_initial['date'] = datetime.datetime.now()
    f_initial['people'] = 0
    #
    form = PartyForm(initial=f_initial)
  return render(
    request,
    'partyfinder/new_party.html',
    {
      'form': form,
    }
  )

def delete_party(request, city, id):
  parties = Party.objects.filter(city=city, id=id)
  if len(parties)> 0:
    party = parties[0]
    city = party.city
    party.delete()
    return HttpResponseRedirect(reverse(
      'partyfinder:parties',
      kwargs={
        'city': city,
      },
    ))
  else:
    raise Http404

def change_party_people(request, city, id, prev_value, delta):
  # A LWT is a way to ensure no surprising race conditions:
  # we can ensure the provided prev_value still matches the column
  delta_num = int(delta)
  #
  cursor = connection.cursor()
  change_applied = cursor.execute(
    'UPDATE party SET people = %s WHERE city=%s AND id=%s IF people = %s',
    (
      delta_num + prev_value,
      city,
      uuid.UUID(id),  # must respect Cassandra type system
      prev_value,
    ),
  ).one()['[applied]']
  if not change_applied:
    lwt_message = '?LWT_FAILED=1'
  else:
    lwt_message = ''
  #
  return HttpResponseRedirect(reverse(
    'partyfinder:party',
    kwargs={
      'city': city,
      'id': id,
    },
  ) + lwt_message)

parties/partyfinder/templates/partyfinder/index.html
<h2>PartyFinder - Index</h2>
<hr>

<form action="{% url 'partyfinder:index' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Browse">
</form>

<hr>
<a href="{% url 'partyfinder:new_party' %}">New</a>

parties/partyfinder/templates/partyfinder/list.html
<h2>PartyFinder - Parties for "{{ city }}:"</h2>
<hr>

{% if parties %}
  <ul>
    {% for party in parties %}
    <li>
      <span style="color: #909090;">{{ party.date | date:'M d, Y' }}</span>
      <a href="{% url 'partyfinder:party' city party.id %}">{{party.name}}</a>
      <span style="margin-left: 15px;">
        <a href="{% url 'partyfinder:delete_party' city party.id %}">[X]</a>
      </span>
    </li>
    {% endfor %}
  </ul>
{% else %}
  <p>Nothing turned up.</p>
{% endif %}

<hr>
<a href="{% url 'partyfinder:index' %}">Home</a>
-
<a href="{% url 'partyfinder:new_party' %}?city={{ city }}">New</a>

parties/partyfinder/templates/partyfinder/new_party.html
<h2>PartyFinder - New Item</h2>
<hr>

<form action="{% url 'partyfinder:new_party' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Post">
</form>

<hr>
<a href="{% url 'partyfinder:index' %}">Home</a>

parties/partyfinder/templates/partyfinder/party.html
<h2>PartyFinder - Details for "<a href="{% url 'partyfinder:parties' party.city %}">{{ party.city }}</a>/{{ party.id }}"</h2>
<hr>

{% if lwt_failed %}
<p style="color: red;">
  Could not update the "people" field. Please try again.
</p>
{% endif %}
<p>
  <strong>Name</strong>: {{ party.name }}
  (<a href="{% url 'partyfinder:delete_party' party.city party.id %}">del</a>)
</p>
<p>
  <strong>Date</strong>: {{ party.date | date:'M d, Y' }}
</p>
<p>
  <strong>People</strong>: {{ party.people }}
  <a href="{% url 'partyfinder:change_party_people' party.city party.id party.people '+1' %}" style="margin-left: 20px;"><button type="button">+1</button></a>
  {% if party.people > 0 %}<a href="{% url 'partyfinder:change_party_people' party.city party.id party.people '-1' %}"><button type="button">-1</button></a>{% endif %}
</p>

<hr>
<a href="{% url 'partyfinder:index' %}">Home</a>
-
<a href="{% url 'partyfinder:new_party' %}?city={{ party.city }}">New</a>